#!/bin/bash
case $1 in
	start)
    rm -rf cache/*
    rm proxify.log
    rm cookies.dat
    php -S 127.0.0.1:9000
	;;
	clean)
    rm -rf cache/*
    rm proxify.log
    rm cookies.dat
	;;
  cache-size)
    du -sh cache
  ;;
	*)
    echo "Use start, cache-size or clean"
	;;
esac
